### ISSUE TITLE
bot doesn't start

### ISSUE THREAD

**Issue by aermike** [Half-Shot/matrix-zammad#14]
when run
yarn run start
error has appear
ed, 06 Jul 2022 10:42:45 GMT [INFO] [MatrixLiteClient (REQ-2)] GET https://matrix.mydomain/_matrix/client/r0/profile/%40helpman%3Amatrix.maydomain
Wed, 06 Jul 2022 10:42:45 GMT [ERROR] [Main] Error occured: TypeError: Cannot read property 'url' of undefined
    at /opt/matrix-zammad/lib/index.js:32:82
    at process._tickCallback (internal/process/next_tick.js:68:7)
Done in 1.80s.

**Comment by kidhab** [comment]
Probably your `default.yaml` misses some configuration options - like `zammad.url`. Have a look at [this](https://github.com/Half-Shot/matrix-zammad/pull/11/commits/0dc66684f2ce4bb805511e578d8534b865e6b62d) PR.

**Comment by aermike** [comment]
Thank you
It passed this phase with new config/production.yaml
but now appear this error
Thu, 28 Jul 2022 09:41:42 GMT [ERROR] [MatrixLiteClient (REQ-4)] { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
Thu, 28 Jul 2022 09:41:42 GMT [ERROR] [Main] Error occured: Error: No config state found
    at StreamRoom.load (/opt/matrix-zammad/lib/rooms/streamroom.js:22:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

How can I add an new state in room?

**Comment by kidhab** [comment]
With Element just enter the room you want use to receive the notifications and send a message with `/devtools` as the only content. Choose the button "Explore room state" (or something similar - I don't use an English interface) and "Send custom room state event".

**Comment by kidhab** [comment]
@Half-Shot maybe you can have a look at  #11 and #12 as they address the questions from this issue.

**Comment by Half-Shot** [comment]
Hi there, sorry I've not maintained this one in a long time. I suspect the functionality will be merged into https://github.com/matrix-org/matrix-hookshot quite soon.

**Comment by aermike** [comment]
insert in room state uk.half-shot.matrix-zammad.roominfo
but get this error
Wed, 10 Aug 2022 11:20:44 GMT [INFO] [MatrixLiteClient (REQ-5)] GET https://matrix.mydomain/_matrix/client/r0/user/%40helpman%3Amatrix.maindomain/rooms/uk.half-shot.matrix-zammad.sync_head/account_data/!ZiTLSvPpCweFdbiGhL%3Amatrix.maindomain
Wed, 10 Aug 2022 11:20:44 GMT [ERROR] [MatrixLiteClient (REQ-5)] { errcode: 'M_INVALID_PARAM',
  error:
   'uk.half-shot.matrix-zammad.sync_head is not a valid room ID' }
Wed, 10 Aug 2022 11:20:44 GMT [ERROR] [Main] Error occured: IncomingMessage {
  _readableState:

![state1](https://user-images.githubusercontent.com/4247309/183890688-8142b969-a130-4901-88ee-25ba15acefd7.PNG)
![state2](https://user-images.githubusercontent.com/4247309/183890706-2306373e-eb88-4c4d-bfa6-ac354d01ddac.PNG)
![state3](https://user-images.githubusercontent.com/4247309/183890714-0ba16f70-2398-4043-bb12-9082d46d5cce.PNG)

**Comment by kidhab** [comment]
You configuration looks ok.
At my setup the bot recently stopped working with the same error message. Maybe this is related to a change caused by a room version update?
